import editors from './editors';
import { chosenRenderer } from './renderers';

export default [
     {
        header: 'Id',
        field: 'id', 
        width: 0,
        type: 'text'
    },
    {
        header: 'NIK',
        field: 'nik', 
        width: 140,
        type: 'text'
    },
    {
        header: 'Nama Penduduk',
        field: 'nama_penduduk', 
        width: 250,
        type: 'text'
    },
    {
        header: 'Tempat Lahir',
        field: 'tempat_lahir', 
        width: 120,
        type: 'text'
    },
    {
        header: 'Tanggal Lahir',
        field: 'tanggal_lahir', 
        type: 'date',
        dateFormat: 'DD/MM/YYYY',
        datePickerConfig: {yearRange: 50},
        correctFormat: true,
        defaultDate: '01/01/1900',
        width: 120,
    },
    {
        header: 'J. Kelamin',
        field: 'jenis_kelamin',
        type: 'dropdown',
        source: ['Laki-Laki', 'Perempuan', 'Tidak Diketahui'],
        width: 110,
        importHeaders: ["Jenis Kelamin"],
    },
     {
        header: 'Pendidikan',
        field: 'pendidikan', 
        type: 'dropdown',
        source: ['Belum masuk TK/Kelompok Bermain', 
                 'Sedang TK/Kelompok Bermain', 
                 'Sedang SD/sederajat', 
                 'Sedang SLTP/Sederajat', 
                 'Sedang SLTA/sederajat', 
                 'Sedang D-1/sederajat', 
                 'Sedang D-2/sederajat',
                 'Sedang D-3/sederajat',
                 'Sedang S-1/sederajat',
                 'Sedang S-2/sederajat',
                 'Sedang S-3/sederajat',
                 'Tamat SD/sederajat',
                 'Tamat SLTP/sederajat',
                 'Tamat SLTA/sederajat',
                 'Tamat D-1/sederajat',
                 'Tamat D-2/sederajat',
                 'Tamat D-3/sedarajat',
                 'Tamat D-4/sederajat',
                 'Tamat S-1/sederajat',
                 'Tamat S-2/sederajat',
                 'Tamat S-3/sederajat',
                 'Sedang SLB A/sederajat',
                 'Sedang SLB B/sederajat',
                 'Sedang SLB C/sederajat',
                 'Tamat SLB A/sederajat',
                 'Tamat SLB B/sederajat',
                 'Tamat SLB C/sederajat',
                 'Tidak pernah sekolah',
                 'Tidak dapat membaca dan menulis huruf Latin/Arab',
                 'Tidak tamat SD/sederajat'],
        width: 150,
    },
    {
        header: 'Agama',
        field: 'agama', 
        type: 'dropdown',
        source: ['Islam', 'Kristen', 'Katholik', 'Hindu', 'Budha', 'Konghuchu', 
        'Aliran Kepercayaan Kepada Tuhan YME', 'Aliran Kepercayaan Lainnya', 'Tidak Diketahui'],
        width: 90,
    },
    {   
        header: 'Status Kawin',
        field: 'status_kawin', 
        type: 'dropdown',
        source: ['Tidak Diketahui', 'Belum Kawin', 'Kawin', 'Janda/Duda'],
        width: 120,
    },
    {
        header: 'Pekerjaan',
        field: 'pekerjaan', 
        type: 'dropdown',
        source: ['Ahli Pengobatan Alternatif',
                 'Akuntan',
                 'Anggota kabinet kementrian',
                 'Anggota Legislatif',
                 'Anggota mahkamah konstitusi',
                 'Apoteker',
                 'Arsitektur/Desainer',
                 'Belum Bekerja',
                 'Bidan swasta',
                 'Bupati/walikota',
                 'Buruh Harian Lepas',
                 'Buruh jasa perdagangan hasil bumi',
                 'Buruh Migran',
                 'Buruh Tani',
                 'Buruh usaha hotel dan penginapan lainnya',
                 'Buruh usaha jasa hiburan dan pariwisata',
                 'Buruh usaha jasa informasi dan komunikasi',
                 'Buruh usaha jasa transportasi dan perhubungan',
                 'Dokter swasta',
                 'Dosen swasta',
                 'Dukun Tradisional',
                 'Dukun/paranormal/supranatural',
                 'Duta besar',
                 'Gubernur',
                 'Guru swasta',
                 'Ibu Rumah Tangga',
                 'Jasa Konsultansi Managemen dan Teknis',
                 'Jasa pengobatan alternatif',
                 'Jasa penyewaan peralatan pesta',
                 'Juru Masak',
                 'Karyawan Honorer',
                 'Karyawan Perusahaan Pemerintah',
                 'Karyawan Perusahaan Swasta',
                 'Kepala Daerah',
                 'Konsultan Managemen dan Teknis',
                 'Kontraktor',
                 'Montir',
                 'Nelayan',
                 'Notaris',
                 'Pedagang barang kelontong',
                 'Pedagang Keliling',
                 'Pegawai Negeri Sipil',
                 'Pelajar',
                 'Pelaut',
                 'Pembantu rumah tangga',
                 'Pemilik perusahaan',
                 'Pemilik usaha hotel dan penginapan lainnya',
                 'Pemilih usaha informasi dan komunikasi',
                 'Pemilik usaha jasa hiburan dan pariwisata',
                 'Pemilik usaha jasa transportasi dan perhubungan',
                 'Pemilik usaha warung, rumah makan dan restoran',
                 'Pemuka Agama',
                 'Pemulung',
                 'Penambang',
                 'Peneliti',
                 'Pengacara',
                 'Pengrajin',
                 'Penrajin industri rumah tangga lainnya',
                 'Pengusaha kecil, menengah dan besar',
                 'Penyiar radio',
                 'Perangkat Desa',
                 'Perawat swasta',
                 'Petani',
                 'Peternak',
                 'Pialang',
                 'Pilot',
                 'POLRI',
                 'Presiden',
                 'Psikiater/Psikolog',
                 'Purnawirawan/Pensiunan',
                 'Satpam/Security',
                 'Seniman/artis',
                 'Sopir',
                 'Tidak Mempunyai Pekerjaan',
                 'TNI',
                 'Tukang Anyaman',
                 'Tukang Batu',
                 'Tukang Cuci',
                 'Tukang Cukur',
                 'Tukang Gigi',
                 'Tukang Jahir',
                 'Tukang Kayu',
                 'Tukang Kue',
                 'Tukang Las',
                 'Tukang Listrik',
                 'Tukang Rias',
                 'Tukang Sumur',
                 'Usaha jasa pengerah tenaga kerja',
                 'Wakil bupati',
                 'Wakil Gubernur',
                 'Wakil presiden',
                 'Wartawan',
                 'Wiraswasta'],
        width: 200,
    },
    {
        header: 'WN',
        field: 'kewarganegaraan', 
        type: 'dropdown',
        source: ['Tidak Diketahui', 'Warga Negara Indonesia', 'Warga Negara Asing', 'Dwi Kewarganegaraan'],
        width: 70,
        importHeaders: ["Kewarganegaraan"],
    },
    {
        header: 'Kompetensi',
        field: 'kompetensi', 
        type: 'dropdown',
        source: ["Tidak Diketahui","Kesehatan","Profesional Bangunan","Profesional Kelistrikan","Profesional Pendidikan"],
        width: 120,
    },
    {
        header: 'No Telepon',
        field: 'no_telepon', 
        type: 'text',
        width: 100,
        importHeaders: ["No Telp"],
    },
    {
        header: 'Email',
        field: 'email', 
        type: 'text',
        width: 100,
        
    },
    {   
        header: 'No Kitas',
        field: 'no_kitas', 
        type: 'text',
        width: 100,
    },
    {
        header: 'No Paspor',
        field: 'no_paspor', 
        type: 'text',
        width: 100,
    },
    {
        header: 'Gol. Darah',
        field: 'golongan_darah', 
        type: 'dropdown',
        source: ['A', 'A+', 'A-', 'B', 'B+', 'B-', 'AB', 'AB+', 'AB-', 'O', 'O+', 'O-', 'Tidak Diketahui'],
        width: 100,
        importHeaders: ["Golongan Darah"],
    },
    {
        header: 'Status Penduduk',
        field: 'status_penduduk', 
        type: 'dropdown',
        source: ['Tidak diketahui', 'Tinggal Tetap', 'Meninggal', 'Pindahan Keluar', 'Pindahan Masuk'],
        width: 140,
    },
    {   
        header: 'Status Tinggal',
        field: 'status_tinggal', 
        type: 'dropdown',
        source: ['Tidak Diketahui', 'Tinggal Tetap', 'Tinggal di luar desa (dalam 1 kab/kota)',
        'Tinggal di luar kota','Tinggal di luar provinsi','Tinggal di luar negeri'],
        width: 150,
    },
    {
        header: 'Kontrasepsi',
        field: 'kontrasepsi', 
        type: 'dropdown',
        source: ['Tidak Diketahui', 'Pil', 'Suntik', 'IUD', 'Kondom', 'Implant', 'MOP', 'MOW'],
        width: 100,
    },
    {
        header: 'Difabilitas',
        field: 'difabilitas', 
        type: 'text',
        chosenOptions: {
          multiple: true,
          data: [
            {
              id: 'lumpuh',
              label: 'Lumpuh'
            },
            {
              id: 'sumbing',
              label: 'Sumbing'
            },
            {
              id: 'tuna_netra',
              label: 'Tuna Netra'
            },
            {
              id: 'tuna_rungu',
              label: 'Tuna Rungu'
            },
            {
              id: 'tuna_wicara',
              label: 'Tuna Wicara'
            }
          ]
        },
        renderer: chosenRenderer,
        editor: editors.chosen,
        width: 200
    },
    {
        header: 'No KK',
        field: 'no_kk', 
        type: 'text'
    },
    {
        header: 'Nama Ayah',
        field: 'nama_ayah', 
        type: 'text'
    },
    {
        header: 'Nama Ibu',
        field: 'nama_ibu', 
        type: 'text'
    },
    {
        header: 'Hubungan Keluarga',
        field: 'hubungan_keluarga', 
        type: 'dropdown',
        source: [
            'Adik',
            'Anak Angkat',
            'Anak Kandung',
            'Anak Tiri',
            'Ayah',
            'Cucu',
            'Famili lain',
            'Ibu',
            'Istri',
            'Kakak',
            'Kakek',
            'Kepala Keluarga',
            'Keponakan',
            'Lainnya',
            'Menantu',
            'Mertua',
            'Nenek',
            'Paman',
            'Sepupu',
            'Suami',
            'Tante',
            'Teman'],
        importHeaders: ["Status Keluarga"],
    },
    {
        header: 'Nama Dusun',
        field: 'nama_dusun', 
        type: 'text'
    },
    {   
        header: 'RW',
        field: 'rw', 
        type: 'text',
        width: 70,
    },
    {
        header: 'RT',
        field: 'rt', 
        type: 'text',
        width: 70,
    },
    {
        header: 'Alamat Jalan',
        field: 'alamat_jalan', 
        type: 'text'
    },
];
