import { Component, ViewContainerRef } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ToastsManager } from 'ng2-toastr';
import ProdeskelService from '../../../../stores/prodeskelService';
import SettingsService from '../../../../stores/settingsService';
import { ProdeskelBase } from '../../base';

@Component({
    selector: 'prodeskel-sdm-usia',
    templateUrl: '../../../../templates/prodeskel/potensi.html',
    styles: [`
        :host {
            display: flex;
        }
    `],
})
export class ProdeskelSdmUsia extends ProdeskelBase {
    title: string = 'Usia Penduduk';
    gridType: string = 'grid_t46a';
    formType: string = 'form_t46a';

    schemaGroups: string[] = [null, 'Laki-laki', 'Perempuan'];
    schemas: { [key: string]: any }[] = [
        { field: 'kode_desa', label: 'Kode Desa', type: 'number', hidden: true, viewHidden: true, groupIndex: 0 },
        { field: 'tanggal', label: 'Tanggal', type: 'date', hidden: true, groupIndex: 0 },
        { field: 'l00', label: '0 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l01', label: '1 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l02', label: '2 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l03', label: '3 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l04', label: '4 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l05', label: '5 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l06', label: '6 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l07', label: '7 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l08', label: '8 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l09', label: '9 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l10', label: '10 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l11', label: '11 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l12', label: '12 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l13', label: '13 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l14', label: '14 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l15', label: '15 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l16', label: '16 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l17', label: '17 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l18', label: '18 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l19', label: '19 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l20', label: '20 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l21', label: '21 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l22', label: '22 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l23', label: '23 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l24', label: '24 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l25', label: '25 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l26', label: '26 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l27', label: '27 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l28', label: '28 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l29', label: '29 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l30', label: '30 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l31', label: '31 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l32', label: '32 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l33', label: '33 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l34', label: '34 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l35', label: '35 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l36', label: '36 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l37', label: '37 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l38', label: '38 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l39', label: '39 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l40', label: '40 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l41', label: '41 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l42', label: '42 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l43', label: '43 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l44', label: '44 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l45', label: '45 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l46', label: '46 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l47', label: '47 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l48', label: '48 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l49', label: '49 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l50', label: '50 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l51', label: '51 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l52', label: '52 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l53', label: '53 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l54', label: '54 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l55', label: '55 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l56', label: '56 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l57', label: '57 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l58', label: '58 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l59', label: '59 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l60', label: '60 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l61', label: '61 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l62', label: '62 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l63', label: '63 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l64', label: '64 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l65', label: '65 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l66', label: '66 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l67', label: '67 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l68', label: '68 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l69', label: '69 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l70', label: '70 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l71', label: '71 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l72', label: '72 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l73', label: '73 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l74', label: '74 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l75', label: '75 Tahun', type: 'number', groupIndex: 1 },
        { field: 'l75a', label: '> 75 Tahun', type: 'number', groupIndex: 1 },
        { field: 'p00', label: '0 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p01', label: '1 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p02', label: '2 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p03', label: '3 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p04', label: '4 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p05', label: '5 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p06', label: '6 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p07', label: '7 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p08', label: '8 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p09', label: '9 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p10', label: '10 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p11', label: '11 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p12', label: '12 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p13', label: '13 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p14', label: '14 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p15', label: '15 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p16', label: '16 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p17', label: '17 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p18', label: '18 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p19', label: '19 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p20', label: '20 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p21', label: '21 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p22', label: '22 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p23', label: '23 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p24', label: '24 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p25', label: '25 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p26', label: '26 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p27', label: '27 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p28', label: '28 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p29', label: '29 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p30', label: '30 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p31', label: '31 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p32', label: '32 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p33', label: '33 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p34', label: '34 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p35', label: '35 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p36', label: '36 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p37', label: '37 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p38', label: '38 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p39', label: '39 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p40', label: '40 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p41', label: '41 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p42', label: '42 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p43', label: '43 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p44', label: '44 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p45', label: '45 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p46', label: '46 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p47', label: '47 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p48', label: '48 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p49', label: '49 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p50', label: '50 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p51', label: '51 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p52', label: '52 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p53', label: '53 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p54', label: '54 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p55', label: '55 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p56', label: '56 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p57', label: '57 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p58', label: '58 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p59', label: '59 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p60', label: '60 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p61', label: '61 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p62', label: '62 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p63', label: '63 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p64', label: '64 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p65', label: '65 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p66', label: '66 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p67', label: '67 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p68', label: '68 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p69', label: '69 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p70', label: '70 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p71', label: '71 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p72', label: '72 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p73', label: '73 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p74', label: '74 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p75', label: '75 Tahun', type: 'number', groupIndex: 2 },
        { field: 'p75a', label: '> 75 Tahun', type: 'number', groupIndex: 2 }
    ]

    constructor(
        toastr: ToastsManager,
        vcr: ViewContainerRef,
        prodeskelService: ProdeskelService,
        settingsService: SettingsService,
    ) {
        super(toastr, vcr, prodeskelService, settingsService);
    }

    setOverrideValues(): void {
        let date = new Date();
        this.overrideValues['tanggal'] = this.encodeDate(date);
    }
}
