// Generated by typings
// Source: node_modules/ng2-select2/ng2-select2.interface.d.ts
declare module '~ng2-select2/ng2-select2.interface' {
/// <reference types="jquery" />
/// <reference types="select2" />
export interface Select2OptionData {
    id: string;
    text: string;
    disabled?: boolean;
    children?: Array<Select2OptionData>;
    additional?: any;
}
export interface Select2TemplateFunction {
    (state: Select2OptionData): JQuery | string;
}
}
declare module 'ng2-select2/ng2-select2.interface' {
export * from '~ng2-select2/ng2-select2.interface';
}

// Generated by typings
// Source: node_modules/ng2-select2/ng2-select2.component.d.ts
declare module '~ng2-select2/ng2-select2.component' {
/// <reference types="select2" />
import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnDestroy, SimpleChanges, Renderer, OnInit } from '@angular/core';
import { Select2OptionData } from '~ng2-select2/ng2-select2.interface';
export class Select2Component implements AfterViewInit, OnChanges, OnDestroy, OnInit {
    private renderer;
    selector: ElementRef;
    data: Array<Select2OptionData>;
    value: string | string[];
    cssImport: boolean;
    width: string;
    disabled: boolean;
    options: Select2Options;
    valueChanged: EventEmitter<{}>;
    private element;
    private check;
    constructor(renderer: Renderer);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private initPlugin();
    private setElementValue(newValue);
    private style;
}
}
declare module 'ng2-select2/ng2-select2.component' {
export * from '~ng2-select2/ng2-select2.component';
}

// Generated by typings
// Source: node_modules/ng2-select2/ng2-select2.d.ts
declare module '~ng2-select2/ng2-select2' {
export { Select2OptionData, Select2TemplateFunction } from '~ng2-select2/ng2-select2.interface';
export { Select2Component } from '~ng2-select2/ng2-select2.component';
export class Select2Module {
}
}
declare module 'ng2-select2/ng2-select2' {
export * from '~ng2-select2/ng2-select2';
}
declare module 'ng2-select2' {
export * from '~ng2-select2/ng2-select2';
}
