let rpjm = [
  [{label: 'BIDANG / JENIS KEGIATAN ', colspan: 2}, 'LOKASI', 'PERKIRAAN VOLUME', 'SASARAN',{label:'WAKTU PELAKSANAAN', colspan:6},{label:'PRAKIRAAN BIAYA DAN SUMBERDANA',colspan:2},{label:'POLA PELAKSANAAN',colspan:3}],
  ['BIDANG / SUB BIDANG','JENIS KEGIATAN','(RT/ RW/ DUSUN )','VOLUME', '/ MANFAAT','THN 1','THN 2','THN 3','THN 4', 'THN 5','THN 6','JUMLAH (Rp)','SUMBER','SWAKELOLA','KERJASAMA','PIHAK KETIGA'],
];

let rkp = [
  [{label: 'BIDANG / JENIS KEGIATAN ', colspan: 2}, 'LOKASI', 'PERKIRAAN VOLUME', 'SASARAN','WAKTU',{label:'PRAKIRAAN BIAYA DAN SUMBERDANA',colspan:2},{label:'POLA PELAKSANAAN',colspan:3},'RENCANA'],
  ['BIDANG / SUB BIDANG','JENIS KEGIATAN','(RT/ RW/ DUSUN )','VOLUME', '/ MANFAAT','PELAKSANAAN','JUMLAH (Rp)','SUMBER','SWAKELOLA','KERJASAMA','PIHAK KETIGA','PELAKSANA KEGIATAN'],
]

export {rpjm,rkp}