// Generated by typings
// Source: node_modules/ng2-toastr/src/toast.d.ts
declare module '~ng2-toastr/src/toast' {
export class Toast {
    type: string;
    message: string;
    title: string;
    data: Object;
    id: number;
    config: any;
    timeoutId: any;
    constructor(type: string, message: string, title?: string, data?: Object);
}
}
declare module 'ng2-toastr/src/toast' {
export * from '~ng2-toastr/src/toast';
}

// Generated by typings
// Source: node_modules/ng2-toastr/src/toast-manager.d.ts
declare module '~ng2-toastr/src/toast-manager' {
import { ComponentRef, ApplicationRef, NgZone, ViewContainerRef, ComponentFactoryResolver } from '@angular/core';
import { ToastOptions } from '~ng2-toastr/src/toast-options';
import { Toast } from '~ng2-toastr/src/toast';
import { Observable } from 'rxjs/Observable';
export class ToastsManager {
    private componentFactoryResolver;
    private ngZone;
    private appRef;
    private options;
    container: ComponentRef<any>;
    private index;
    private toastClicked;
    private _rootViewContainerRef;
    constructor(componentFactoryResolver: ComponentFactoryResolver, ngZone: NgZone, appRef: ApplicationRef, options: ToastOptions);
    setRootViewContainerRef(vRef: ViewContainerRef): void;
    onClickToast(): Observable<Toast>;
    show(toast: Toast, options?: Object): Promise<Toast>;
    createTimeout(toast: Toast): any;
    setupToast(toast: Toast, options?: any): Toast;
    private _onToastClicked(toast);
    dismissToast(toast: Toast): void;
    clearToast(toast: Toast): void;
    clearAllToasts(): void;
    dispose(): void;
    error(message: string, title?: string, options?: any): Promise<Toast>;
    info(message: string, title?: string, options?: any): Promise<Toast>;
    success(message: string, title?: string, options?: any): Promise<Toast>;
    warning(message: string, title?: string, options?: any): Promise<Toast>;
    custom(message: string, title?: string, options?: any): Promise<Toast>;
}
}
declare module 'ng2-toastr/src/toast-manager' {
export * from '~ng2-toastr/src/toast-manager';
}

// Generated by typings
// Source: node_modules/ng2-toastr/src/toast-container.component.d.ts
declare module '~ng2-toastr/src/toast-container.component' {
import { ChangeDetectorRef, NgZone, OnDestroy, AnimationTransitionEvent } from '@angular/core';
import { Toast } from '~ng2-toastr/src/toast';
import { ToastOptions } from '~ng2-toastr/src/toast-options';
import { DomSanitizer } from '@angular/platform-browser';
import 'rxjs/add/operator/first';
import { Observable } from 'rxjs/Observable';
export class ToastContainer implements OnDestroy {
    private sanitizer;
    private cdr;
    private _zone;
    position: string;
    messageClass: string;
    titleClass: string;
    positionClass: string;
    maxShown: number;
    newestOnTop: boolean;
    animate: string;
    toasts: Toast[];
    private _fresh;
    private onToastClicked;
    private _onEnter;
    private _onExit;
    constructor(sanitizer: DomSanitizer, cdr: ChangeDetectorRef, _zone: NgZone, options: ToastOptions);
    onEnter(): Observable<void>;
    onExit(): Observable<void>;
    addToast(toast: Toast): void;
    removeToast(toast: Toast): void;
    removeAllToasts(): void;
    clicked(toast: Toast): void;
    anyToast(): boolean;
    findToast(toastId: number): Toast | void;
    onAnimationEnd(event: AnimationTransitionEvent): void;
    private _ngExit();
    ngOnDestroy(): void;
}
}
declare module 'ng2-toastr/src/toast-container.component' {
export * from '~ng2-toastr/src/toast-container.component';
}

// Generated by typings
// Source: node_modules/ng2-toastr/src/toast-options.d.ts
declare module '~ng2-toastr/src/toast-options' {
export class ToastOptions {
    positionClass: string;
    maxShown: number;
    newestOnTop: boolean;
    animate: string;
    toastLife: number;
    enableHTML: boolean;
    dismiss: string;
    messageClass: string;
    titleClass: string;
    showCloseButton: boolean;
    constructor();
}
}
declare module 'ng2-toastr/src/toast-options' {
export * from '~ng2-toastr/src/toast-options';
}

// Generated by typings
// Source: node_modules/ng2-toastr/src/toast.module.d.ts
declare module '~ng2-toastr/src/toast.module' {
import { ModuleWithProviders } from '@angular/core';
export class ToastModule {
    static forRoot(): ModuleWithProviders;
}
}
declare module 'ng2-toastr/src/toast.module' {
export * from '~ng2-toastr/src/toast.module';
}

// Generated by typings
// Source: node_modules/ng2-toastr/ng2-toastr.d.ts
declare module '~ng2-toastr/ng2-toastr' {
export { Toast } from '~ng2-toastr/src/toast';
export { ToastsManager } from '~ng2-toastr/src/toast-manager';
export { ToastContainer } from '~ng2-toastr/src/toast-container.component';
export { ToastOptions } from '~ng2-toastr/src/toast-options';
export { ToastModule } from '~ng2-toastr/src/toast.module';
}
declare module 'ng2-toastr/ng2-toastr' {
export * from '~ng2-toastr/ng2-toastr';
}
declare module 'ng2-toastr' {
export * from '~ng2-toastr/ng2-toastr';
}
