// Generated by typings
// Source: node_modules/@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/leaflet-draw.module.d.ts
declare module '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/leaflet-draw.module' {
import { ModuleWithProviders } from '@angular/core';
export class LeafletDrawModule {
    static forRoot(): ModuleWithProviders;
}
}
declare module '@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/leaflet-draw.module' {
export * from '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/leaflet-draw.module';
}

// Generated by typings
// Source: node_modules/@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts
declare module '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive' {
/// <reference types="leaflet-draw" />
/// <reference types="leaflet" />
import { OnChanges, OnInit, SimpleChange } from '@angular/core';
import * as L from 'leaflet';
import 'leaflet-draw';
import { LeafletDirective, LeafletDirectiveWrapper } from '@asymmetrik/angular2-leaflet';
export class LeafletDrawDirective implements OnChanges, OnInit {
    leafletDirective: LeafletDirectiveWrapper;
    drawControl: L.Control.Draw;
    featureGroup: L.FeatureGroup;
    drawOptions: L.Control.DrawConstructorOptions;
    constructor(leafletDirective: LeafletDirective);
    ngOnInit(): void;
    ngOnChanges(changes: {
        [key: string]: SimpleChange;
    }): void;
    initializeDrawOptions(options: L.Control.DrawConstructorOptions): L.Control.DrawConstructorOptions;
}
}
declare module '@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive' {
export * from '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive';
}

// Generated by typings
// Source: node_modules/@asymmetrik/angular2-leaflet-draw/dist/index.d.ts
declare module '~@asymmetrik/angular2-leaflet-draw/dist/index' {
export { LeafletDrawModule } from '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/leaflet-draw.module';
export { LeafletDrawDirective } from '~@asymmetrik/angular2-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive';
}
declare module '@asymmetrik/angular2-leaflet-draw/dist/index' {
export * from '~@asymmetrik/angular2-leaflet-draw/dist/index';
}
declare module '@asymmetrik/angular2-leaflet-draw' {
export * from '~@asymmetrik/angular2-leaflet-draw/dist/index';
}
